version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: production
      FLASK_APP: app.py
      SECRET_KEY: supersecretkey123
      DATABASE_URL: sqlite:///quotes.db
      ADMIN_API_KEY: changeme123
      RATE_LIMIT: 60/minute
