from motivation_api.app import app, db
from motivation_api.models import Quote

quotes_list = [
    {"text": "The best way to get started is to quit talking and begin doing.", "author": "Walt Disney"},
    {"text": "Don't let yesterday take up too much of today.", "author": "Will Rogers"},
    {"text": "It's not whether you get knocked down, it's whether you get up.", "author": "Vince Lombardi"},
    {"text": "If you are working on something exciting, it will keep you motivated.", "author": "Unknown"},
    {"text": "Success is not in what you have, but who you are.", "author": "Bo Bennett"},
    {"text": "Your limitation—it's only your imagination.", "author": "Unknown"},
    {"text": "Push yourself, because no one else is going to do it for you.", "author": "Unknown"},
    {"text": "Great things never come from comfort zones.", "author": "Unknown"},
    {"text": "Dream it. Wish it. Do it.", "author": "Unknown"},
    {"text": "Success doesn’t just find you. You have to go out and get it.", "author": "Unknown"},
    {"text": "The harder you work for something, the greater you’ll feel when you achieve it.", "author": "Unknown"},
    {"text": "Don’t stop when you’re tired. Stop when you’re done.", "author": "Unknown"},
    {"text": "Wake up with determination. Go to bed with satisfaction.", "author": "Unknown"},
    {"text": "Do something today that your future self will thank you for.", "author": "Unknown"},
    {"text": "Little things make big days.", "author": "Unknown"},
    {"text": "It’s going to be hard, but hard does not mean impossible.", "author": "Unknown"},
    {"text": "Don’t wait for opportunity. Create it.", "author": "Unknown"},
    {"text": "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.", "author": "Unknown"},
    {"text": "The key to success is to focus on goals, not obstacles.", "author": "Unknown"},
    {"text": "Dream bigger. Do bigger.", "author": "Unknown"},
    {"text": "Don’t watch the clock; do what it does. Keep going.", "author": "Sam Levenson"},
    {"text": "Keep your eyes on the stars, and your feet on the ground.", "author": "Theodore Roosevelt"},
    {"text": "Opportunities don't happen. You create them.", "author": "Chris Grosser"},
    {"text": "Everything you can imagine is real.", "author": "Pablo Picasso"},
    {"text": "Act as if what you do makes a difference. It does.", "author": "William James"},
    {"text": "Believe you can and you're halfway there.", "author": "Theodore Roosevelt"},
    {"text": "Failure is the condiment that gives success its flavor.", "author": "Truman Capote"},
    {"text": "Don’t limit your challenges. Challenge your limits.", "author": "Unknown"},
    {"text": "What we achieve inwardly will change outer reality.", "author": "Plutarch"},
    {"text": "Motivation is what gets you started. Habit is what keeps you going.", "author": "Jim Ryun"},
    {"text": "The only way to do great work is to love what you do.", "author": "Steve Jobs"},
    {"text": "Start where you are. Use what you have. Do what you can.", "author": "Arthur Ashe"},
    {"text": "If you can dream it, you can do it.", "author": "Walt Disney"},
    {"text": "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.", "author": "Roy T. Bennett"},
    {"text": "It always seems impossible until it’s done.", "author": "Nelson Mandela"},
    {"text": "Small daily improvements over time lead to stunning results.", "author": "Robin Sharma"},
    {"text": "Success usually comes to those who are too busy to be looking for it.", "author": "Henry David Thoreau"},
    {"text": "Hustle in silence and let your success make the noise.", "author": "Unknown"},
    {"text": "You don’t have to be great to start, but you have to start to be great.", "author": "Zig Ziglar"},
    {"text": "Do not wait to strike till the iron is hot; but make it hot by striking.", "author": "William Butler Yeats"},
    {"text": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt"},
    {"text": "Action is the foundational key to all success.", "author": "Pablo Picasso"},
    {"text": "Your passion is waiting for your courage to catch up.", "author": "Isabelle Lafleche"},
    {"text": "Magic is believing in yourself. If you can do that, you can make anything happen.", "author": "Johann Wolfgang von Goethe"},
    {"text": "Don’t count the days, make the days count.", "author": "Muhammad Ali"},
    {"text": "Success is the sum of small efforts, repeated day in and day out.", "author": "Robert Collier"},
    {"text": "You are braver than you believe, stronger than you seem, and smarter than you think.", "author": "A.A. Milne"},
    {"text": "Everything you’ve ever wanted is on the other side of fear.", "author": "George Addair"},
    {"text": "The future depends on what you do today.", "author": "Mahatma Gandhi"},
    {"text": "Opportunities multiply as they are seized.", "author": "Sun Tzu"},
    {"text": "Don’t be afraid to give up the good to go for the great.", "author": "John D. Rockefeller"},
    {"text": "The harder the conflict, the more glorious the triumph.", "author": "Thomas Paine"},
    {"text": "You don’t need to see the whole staircase, just take the first step.", "author": "Martin Luther King Jr."},
    {"text": "Courage doesn’t always roar. Sometimes courage is the quiet voice at the end of the day saying, ‘I will try again tomorrow.’", "author": "Mary Anne Radmacher"},
    {"text": "Do what you can with all you have, wherever you are.", "author": "Theodore Roosevelt"},
    {"text": "Don’t let what you cannot do interfere with what you can do.", "author": "John Wooden"},
    {"text": "A year from now you may wish you had started today.", "author": "Karen Lamb"},
    {"text": "I never dreamed about success. I worked for it.", "author": "Estee Lauder"},
    {"text": "We generate fears while we sit. We overcome them by action.", "author": "Dr. Henry Link"},
    {"text": "The man who has confidence in himself gains the confidence of others.", "author": "Hasidic Proverb"},
    {"text": "Do not be embarrassed by your failures, learn from them and start again.", "author": "Richard Branson"},
    {"text": "When we strive to become better than we are, everything around us becomes better too.", "author": "Paulo Coelho"},
    {"text": "The secret of getting ahead is getting started.", "author": "Mark Twain"},
    {"text": "Dreams don’t work unless you do.", "author": "John C. Maxwell"},
    {"text": "Keep going. Be all in.", "author": "Bryan Hutchinson"},
    {"text": "Your life does not get better by chance, it gets better by change.", "author": "Jim Rohn"},
    {"text": "The way to get started is to quit talking and begin doing.", "author": "Walt Disney"},
    {"text": "Success is walking from failure to failure with no loss of enthusiasm.", "author": "Winston Churchill"},
    {"text": "Don’t wish it were easier. Wish you were better.", "author": "Jim Rohn"},
    {"text": "Happiness is not something ready-made. It comes from your own actions.", "author": "Dalai Lama"},
    {"text": "You can never cross the ocean until you have the courage to lose sight of the shore.", "author": "Christopher Columbus"},
    {"text": "Start each day with a positive thought and a grateful heart.", "author": "Roy T. Bennett"},
    {"text": "The only person you are destined to become is the person you decide to be.", "author": "Ralph Waldo Emerson"},
    {"text": "Don’t wait. The time will never be just right.", "author": "Napoleon Hill"},
    {"text": "If you want to lift yourself up, lift up someone else.", "author": "Booker T. Washington"},
    {"text": "Great minds discuss ideas; average minds discuss events; small minds discuss people.", "author": "Eleanor Roosevelt"},
    {"text": "Do not go where the path may lead, go instead where there is no path and leave a trail.", "author": "Ralph Waldo Emerson"},
    {"text": "You miss 100% of the shots you don’t take.", "author": "Wayne Gretzky"},
    {"text": "A person who never made a mistake never tried anything new.", "author": "Albert Einstein"},
    {"text": "Success is liking yourself, liking what you do, and liking how you do it.", "author": "Maya Angelou"},
    {"text": "Strive not to be a success, but rather to be of value.", "author": "Albert Einstein"},
    {"text": "Life is 10% what happens to us and 90% how we react to it.", "author": "Charles R. Swindoll"},
    {"text": "You must expect great things of yourself before you can do them.", "author": "Michael Jordan"},
    {"text": "Don’t be afraid to fail big, for big failure is a stepping stone to success.", "author": "Unknown"},
    {"text": "Work hard in silence, let success make the noise.", "author": "Frank Ocean"},
    {"text": "Your time is limited, so don’t waste it living someone else’s life.", "author": "Steve Jobs"},
    {"text": "I find that the harder I work, the more luck I seem to have.", "author": "Thomas Jefferson"},
    {"text": "Do not wait for leaders; do it alone, person to person.", "author": "Mother Teresa"},
]

def seed_quotes():
    with app.app_context():  # <-- Push Flask application context
        for q in quotes_list:
            # Avoid duplicating quotes if they already exist
            exists = Quote.query.filter_by(text=q["text"]).first()
            if not exists:
                quote = Quote(text=q["text"], author=q["author"])
                db.session.add(quote)
        db.session.commit()
        print(f"Seeded {len(quotes_list)} quotes successfully!")
if __name__ == "__main__":
    seed_quotes()
